# JamieBot/app/state_machine/states.py
from enum import Enum

class ConversationState(str, Enum):
    ENTRY = "ENTRY"
    ENTRY_SOCIAL = "ENTRY_SOCIAL"
    
    # Funnel Stages
    STAGE_1_PATTERN = "STAGE_1_PATTERN"
    STAGE_2_TIME_COST = "STAGE_2_TIME_COST"
    STAGE_3_ADDITIONAL = "STAGE_3_ADDITIONAL"
    STAGE_4_FAILED_SOLUTIONS = "STAGE_4_FAILED_SOLUTIONS"
    STAGE_5_GOAL = "STAGE_5_GOAL"
    STAGE_6_GAP = "STAGE_6_GAP"
    STAGE_7_REFRAME = "STAGE_7_REFRAME"
    STAGE_8_INTRO_COACHING = "STAGE_8_INTRO_COACHING"
    STAGE_9_PROGRAM_FRAMING = "STAGE_9_PROGRAM_FRAMING"
    
    # Qualification
    STAGE_10_QUAL_LOCATION = "STAGE_10_QUAL_LOCATION"
    STAGE_10_QUAL_AGE = "STAGE_10_QUAL_AGE"
    STAGE_10_QUAL_RELATIONSHIP = "STAGE_10_QUAL_RELATIONSHIP"
    STAGE_10_QUAL_FITNESS = "STAGE_10_QUAL_FITNESS"
    STAGE_10_QUAL_FINANCE = "STAGE_10_QUAL_FINANCE"
    
    # Routing
    ROUTE_HIGH_TICKET = "ROUTE_HIGH_TICKET"
    ROUTE_LOW_TICKET = "ROUTE_LOW_TICKET"
    
    # Post-Link Handling
    POST_LINK_FLOW = "POST_LINK_FLOW"
    
    END = "END"
